version: '2'
services:
 influxdb:
  image: influxdb:1.4.2
  volumes:
   - ./data/influxdb/data:/var/lib/influxdb
  ports:
   - 127.0.0.1:8086:8086

 jenkins:
  image: jenkins/jenkins:2.101-alpine
  depends_on:
   - influxdb
  volumes:
   - ./data/jenkins/data:/var/jenkins_home
  ports:
   - 127.0.0.1:8080:8080
   - 127.0.0.1:50000:50000

 grafana:
  image: grafana/grafana:4.6.3
  depends_on:
   - influxdb
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=admin
   - GF_INSTALL_PLUGINS=neocat-cal-heatmap-panel,vonage-status-panel,briangann-gauge-panel,jdbranham-diagram-panel
   - GF_SERVER_DOMAIN=localhost
  volumes:
   - ./data/grafana/data:/var/lib/grafana
  ports:
   - 127.0.0.1:3000:3000

 telegraf:
  image: telegraf:1.5.1
  depends_on:
   - influxdb
  volumes:
   - ./data/telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
